name: Verify Documentation

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'astro.config.mjs'
      - 'package.json'
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'astro.config.mjs'
      - 'package.json'

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.11

      - name: Install dependencies
        run: bun install

      - name: Run Astro check
        run: bun run docs:check

      - name: Build documentation
        run: bun run docs:build
